### ISSUE TITLE
NOT working

### ISSUE THREAD

**Issue by slightin** [IsThereAnyDeal/AugmentedSteam#1767]
### Actual Behavior
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/67229521/673e64a9-0083-4c04-9286-80996dfc2b3d)
The console reports the following error：
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at G._replaceAccountName (app.js:1:46204)
    at G.init (app.js:1:48076)
    at run.constructor.run (app.js:1:70361)

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Microsoft Edge 116.0.1938.81 (Stable) (x64)

**Comment by MxtOUT** [comment]
#1748
